name: Build Test App

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Npm Install
        run: |
          npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RoboPro-Desktop.exe
          path: dist/RoboPro-Desktop*.exe
          retention-days: 1

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Python 3.10
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Npm Install
        run: npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RoboPro-Desktop.dmg
          path: dist/RoboPro-Desktop*.dmg
          retention-days: 1

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Npm Install
        run: npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RoboPro-Desktop.deb
          path: dist/RoboPro-Desktop*.deb
          retention-days: 1
